"""
Django settings for quiz_project project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8x@xezeii4inx1skk*kyl4_s1+j-r2p$vw^evp25cff2rt$7ok'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_prometheus',
    'storages',
    # Third-party
    'rest_framework',
    'channels',
    # Local apps
    'accounts',
    'quizzes',
    'submissions',
    'realtime',
    'core',
    'api',
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.AttemptGuardMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = 'quiz_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.global_ui',
            ],
        },
    },
]

WSGI_APPLICATION = 'quiz_project.wsgi.application'
# ASGI for Channels (configured later for realtime)
ASGI_APPLICATION = 'quiz_project.asgi.application'


# Database (Postgres via DATABASE_URL, fallback to SQLite)
from urllib.parse import urlparse

DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    # Expected formats: postgres://user:pass@host:port/dbname or postgresql://
    # Minimal parse; rely on dj-database-url if added later.
    url = urlparse(DATABASE_URL)
    ENGINE = 'django.db.backends.postgresql'
    DB_NAME = url.path.lstrip('/')
    DATABASES = {
        'default': {
            'ENGINE': ENGINE,
            'NAME': DB_NAME,
            'USER': url.username or '',
            'PASSWORD': url.password or '',
            'HOST': url.hostname or '',
            'PORT': url.port or '',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# Ensure leading slash so ASGI static wrapper matches path prefix (previous value caused 404s under Daphne)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# django-prometheus will collect default Django & DB metrics automatically.

# ----------------------------------------------------------------------------
# Storage (S3-compatible for media & optionally static)
# ----------------------------------------------------------------------------
# Environment variables (no hardcoded values)
# Required:
#   AWS_STORAGE_BUCKET_NAME
#   AWS_ACCESS_KEY_ID
#   AWS_SECRET_ACCESS_KEY
# Optional / for non-AWS endpoints (e.g. MinIO):
#   AWS_S3_ENDPOINT_URL (e.g. http://minio:9000 or http://127.0.0.1:9000)
#   AWS_S3_REGION_NAME (default empty)
#   AWS_S3_SIGNATURE_VERSION (e.g. s3v4)
#   AWS_QUERYSTRING_AUTH ("0" to disable signed URLs for public-read buckets)
# Static vs media separation:
#   USE_SEPARATE_STATIC_BUCKET=1 and STATIC_AWS_STORAGE_BUCKET_NAME to override

USE_S3 = os.environ.get("USE_S3", "1") == "1"
if USE_S3:
    # Use custom prefixed storage classes (media & static) backed by same or separate buckets
    DEFAULT_FILE_STORAGE = "quiz_project.storage.MediaRootS3Boto3Storage"
    STATICFILES_STORAGE = "quiz_project.storage.StaticRootS3Boto3Storage"
    AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME", "")
    AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID", "")
    AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY", "")
    AWS_S3_ENDPOINT_URL = os.environ.get("AWS_S3_ENDPOINT_URL") or None
    AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME") or None
    AWS_S3_SIGNATURE_VERSION = os.environ.get("AWS_S3_SIGNATURE_VERSION") or None
    AWS_QUERYSTRING_AUTH = os.environ.get("AWS_QUERYSTRING_AUTH", "1") == "1"
    AWS_DEFAULT_ACL = os.environ.get("AWS_DEFAULT_ACL") or None  # e.g. 'public-read'
    AWS_S3_OBJECT_PARAMETERS = {}

    # Static bucket override (optional)
    STATIC_AWS_STORAGE_BUCKET_NAME = os.environ.get("STATIC_AWS_STORAGE_BUCKET_NAME", AWS_STORAGE_BUCKET_NAME)
    MEDIA_AWS_STORAGE_BUCKET_NAME = os.environ.get("MEDIA_AWS_STORAGE_BUCKET_NAME", AWS_STORAGE_BUCKET_NAME)

    # Optional media/static URLs override
    MEDIA_URL = os.environ.get("MEDIA_URL", "/media/")
    # Public / private bucket separation (optional)
    PUBLIC_MEDIA_AWS_STORAGE_BUCKET_NAME = os.environ.get("PUBLIC_MEDIA_AWS_STORAGE_BUCKET_NAME") or AWS_STORAGE_BUCKET_NAME
    PRIVATE_MEDIA_AWS_STORAGE_BUCKET_NAME = os.environ.get("PRIVATE_MEDIA_AWS_STORAGE_BUCKET_NAME") or AWS_STORAGE_BUCKET_NAME

# Local dev fallback keeps existing STATIC_URL configuration.

# Authentication backends and auth settings
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'accounts.backends.EmailOrUsernameBackend',
]

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Realtime / Channels configuration
import os

USE_REDIS_CHANNEL_LAYER = os.environ.get("USE_REDIS_CHANNEL_LAYER", "1") == "1"
REDIS_URL = os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/0")

if USE_REDIS_CHANNEL_LAYER:
    _redis_channels_ok = True
    try:
        # Lightweight connectivity probe (non-fatal)
        import redis  # type: ignore
        _tmp = redis.Redis.from_url(REDIS_URL, socket_connect_timeout=0.2, socket_timeout=0.2)
        _tmp.ping()
    except Exception:
        _redis_channels_ok = False
    if _redis_channels_ok:
        CHANNEL_LAYERS = {
            "default": {
                "BACKEND": "channels_redis.core.RedisChannelLayer",
                "CONFIG": {"hosts": [REDIS_URL]},
            }
        }
    else:
        CHANNEL_LAYERS = {  # Fallback
            "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}
        }
else:
    CHANNEL_LAYERS = {
        "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}
    }

# Cache: prefer Redis if available, fallback to locmem
USE_REDIS_CACHE = os.environ.get("USE_REDIS_CACHE", "0") == "1"  # default off until stable
REDIS_CACHE_URL = os.environ.get("REDIS_CACHE_URL", "redis://127.0.0.1:6379/1")
if USE_REDIS_CACHE:
    _redis_cache_ok = False
    try:  # Attempt a fast ping to avoid runtime 500s if Redis absent
        import redis  # type: ignore
        _rc = redis.Redis.from_url(REDIS_CACHE_URL, socket_connect_timeout=0.2, socket_timeout=0.2)
        _rc.ping()
        _redis_cache_ok = True
    except Exception:  # pragma: no cover - best effort
        _redis_cache_ok = False
    if _redis_cache_ok:
        CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.redis.RedisCache",
                "LOCATION": REDIS_CACHE_URL,
            }
        }
    else:
        CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
                "LOCATION": "quizzy-local-cache",
            }
        }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "quizzy-local-cache",
        }
    }

# Global UI / feature configuration
SITE_NAME = "Quizzy"
APP_VERSION = "0.1.0"
ENV_LABEL = "DEV" if DEBUG else ""
DEFAULT_THEME = "light"
FEATURE_FLAGS = {
    "realtime": True,
    "bootstrap_ui": True,
}
MAX_QUIZ_ATTEMPTS = 3

# Email / SMTP (local mail server at 127.0.0.1:1025)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = '127.0.0.1'
EMAIL_PORT = 1025
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = False
DEFAULT_FROM_EMAIL = 'Quizzy <noreply@quizzy.local>'

